visualization_grid:
  RowVisualizer:
    input_mapping:
      global: [B: 0, D: ':']
      input: ['inputs', index: 0]
      segmentation: ['target', index: 0]
      prediction: 'prediction'  # this needs to be here in order for the global slicing to be applied
      target: 'target'

    pad_width: 1
    pad_value: .2
    upsampling_factor: 3

    visualizers:

      # visualize raw input
      - InputVisualizer:
          cmap: inferno

      # visualize gt segmentation
      - SegmentationVisualizer:
          #background_color: [0, 0, 0]
          background_label: 0

      # visualize segmentation predictions
      - PredictionVisualizer:
          input_mapping:
            prediction: [C: '0', pre: 'sigmoid']
          value_range: [0, 1]

      # visualize ground-truth orientations
      - RGBVisualizer:
          input_mapping:
            image: ['target', index: 1]
          value_range: [-1, 1]
          background_label: 0
          background_color: [0, 0, 0]

      # visualize masked predicted orientations
      - OverlayVisualizer:
          visualizers:
            - MaskVisualizer:
                input_mapping:
                  image: ['segmentation']
                mask_label: 0
            - SegTags.visualizers.OrientationVisualizer3D:
                input_mapping:
                  prediction: [C: '1:']

      # visualize unmasked predicted orientations
      - SegTags.visualizers.OrientationVisualizer3D:
          input_mapping:
            prediction: [C: '1:']

      # visualize which side of the cube was predicted
      - RGBVisualizer:
          input_mapping:
            image: ['prediction', pre: {softmax: {dim: 1}}, C: '-3:']
          value_range: [0, 1]

      # visualize coordinate predictions
      - PredictionVisualizer:
          input_mapping:
            prediction: [C: '1:7']




